### ISSUE TITLE
Server crash on file access

### ISSUE THREAD

**Issue by Prodigal-Monk** [godarklight/DarkBackup#1]
It looks like the plugin tried to make a backup at the same time that server was trying to write to Subspace.txt and caused an error in the server with simultaneous file access. It only pushed the error to the console, nothing was written to logs.

**Comment by godarklight** [comment]
I just had to check, this crash is only possible on LMP and it crashes on the server side, not the plugin side
https://github.com/godarklight/DarkMultiPlayer/blob/master/Server/ClientHandler.cs#L452-L464
https://github.com/LunaMultiplayer/LunaMultiplayer/blob/master/Server/Server/MessageReceiver.cs#L76

This commit by dagger should fix the crash https://github.com/LunaMultiplayer/LunaMultiplayer/commit/8961db70d00e93874423615b4dc5b9bb0df75520
